apiVersion: apps/v1
kind: Deployment

metadata:
  name: k8s-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: k8s-demo

  template:
    metadata:
      labels:
        app: k8s-demo

    spec:
      containers:
      - name: k8s-demo
        image: k8s-demo:v1

        imagePullPolicy: Never

        ports:
        - containerPort: 3000